### ISSUE TITLE
Add Run2.2i DIA output

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-dc2-dm-data#13]
I'm wondering about adding the new data transfer from CC for DIA tract 3828 that is now at NERSC.  Perhaps named: `2.2i_dia_y2_t3828`?

> This is building DC2 y1 template and looking for transients in WFD y2 exposures : image differencing, associations, forced photometry on calexp, and forced photometry on the reference template have been run.

https://lsstc.slack.com/archives/CJFR141PY/p1583656051012600

Additionally, should we remove or update `'dia_2020Jan': '/global/cscratch1/sd/bos0109/templates_rect',`?  Any opinions @wmwv @BrunoSanchez ?

**Comment by BrunoSanchez** [comment]
I think the naming is perfect. I agree on the addition.

Regarding the second mentioned dataset, it is different since they are for different runs.
Also, the `dia_2020Jan` is still my main dataset and I am using it at the moment.
I would ask for it to not be removed, and if you need me to transfer it to a different area I can do it.

**Comment by heather999** [comment]
Ok - I can certainly leave it! Would you like to transfer that dia_2020Jan to an area on CFS?  It doesn't matter to me - but that way you wouldn't have to worry about purging.

**Comment by yymao** [comment]
Fixed by #12
